language: node_js
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - node
  - 6
cache: yarn
install:
  - yarn global add polymer-cli
  - polymer install
before_script:
  # - polymer lint
script:
  - xvfb-run polymer test
