language: node_js
dist: trusty
sudo: required
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  yarn: true
install:
  - yarn global add polymer-cli
  - polymer install
before_script:
  - polymer lint
script:
  - xvfb-run polymer test
